#!/bin/bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git rev-list --max-parents=0 HEAD)
fi

currentYear=$(date +%Y)
let previousYear=currentYear-1

for file in `git diff-index --cached $against | grep " 100644" | awk '{print $6}' | grep -E "^(library|plugins|software|tests).*\.(c|cpp|cxx|h|py|qss)$"`
do
    for year in $(seq 2019 $previousYear)
    do
      if grep -q "Copyright (C) $year.*The Talipot developers" "$file"
      then
        sed -i "s/Copyright (C) $year.*/Copyright (C) $year-$currentYear  The Talipot developers/" "$file"
        git add "$file"
      fi
    done
done
