#!/bin/bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git rev-list --max-parents=0 HEAD)
fi

currentYear=$(date +%Y)

for file in `git diff-index --cached $against | grep " 100644" | awk '{print $6}' | grep -v -E "^(thirdparty|cmake-format).*$" | grep -E ".*(CMakeLists\.txt|.*\.cmake.*)$"`
do
  cmake-format -i "$file"
  git add "$file"
done
