# Find the fontconfig library and its include directory

FIND_PATH(FONTCONFIG_INCLUDE_DIR fontconfig/fontconfig.h)

FIND_LIBRARY(FONTCONFIG_LIBRARY NAMES fontconfig)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FontConfig DEFAULT_MSG FONTCONFIG_LIBRARY
                                  FONTCONFIG_INCLUDE_DIR)

IF(FONTCONFIG_FOUND)
  SET(FONTCONFIG_LIBRARIES ${FONTCONFIG_LIBRARY})
ENDIF()

MARK_AS_ADVANCED(FONTCONFIG_INCLUDE_DIR FONTCONFIG_LIBRARY FONTCONFIG_LIBRARIES)
