name: ubuntu-qt6-build
on: [push, pull_request]
jobs:
  ubuntu:
    name: Talipot Qt6 build on Ubuntu 20.04
    runs-on: ubuntu-20.04
    env:
      LD_LIBRARY_PATH: /opt/Qt/6.2.0/gcc_64/lib
    steps:
      - name: Checkout Talipot code
        uses: actions/checkout@v2
      - name: Apt update
        run: sudo apt update
      - name: Install Talipot build dependencies
        run: sudo apt install
          cmake
          ccache
          curl
          ninja-build
          libqhull-dev
          libyajl-dev
          libgit2-dev
          libgraphviz-dev
          libpython3-dev
          libcppunit-dev
          binutils-dev
          libzstd-dev
          libglew-dev
          libfreetype6-dev
          libfribidi-dev
          libfontconfig-dev
          python3
          python3-pip
          doxygen
          graphviz
          libxcomposite-dev
          libxtst-dev
          libdbus-1-dev
          libasound2-dev
          libvulkan-dev
          libxkbcommon-dev
          libxkbcommon-x11-dev
          libxcb1-dev
          libxcb-image0-dev
          libxcb-icccm4-dev
          libxcb-keysyms1-dev
          libxcb-randr0-dev
          libxcb-render-util0-dev
          libxcb-xkb-dev
      - name: Install Qt6
        run: |
          curl -O https://raw.githubusercontent.com/anlambert/qbs/install-script-fixes/scripts/install-qt.sh
          chmod +x install-qt.sh
          sudo ./install-qt.sh --version 6.2.0 \
            qtbase \
            icu \
            qt5compat \
            qtimageformats \
            qtpositioning \
            qtdeclarative \
            qtwebengine \
            qtwebsockets \
            qtwebchannel \
            qtsvg
      - name: Install sphinx
        run: sudo pip install sphinx
      - name: Prepare ccache timestamp
        id: get-current-date
        run: |
          echo "::set-output name=date::$(date -u "+%Y-%m-%d-%H-%m-%S")"
        shell: bash
      - name: Cache files
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ubuntu-qt6-build-ccache-${{ steps.get-current-date.outputs.date }}
          restore-keys: |
            ubuntu-qt6-build-ccache-
      - name: Create build directory
        run: mkdir build
      - name: Configure Talipot build with CMake
        working-directory: ./build
        run: cmake .. -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=$PWD/install
          -DTALIPOT_USE_QT6=ON
          -DCMAKE_PREFIX_PATH=/opt/Qt/6.2.0/gcc_64
          -DTALIPOT_BUILD_TESTS=ON
          -DTALIPOT_USE_CCACHE=ON
      - name: Talipot build
        working-directory: ./build
        run: ninja -j4
      - name: Install Talipot
        working-directory: ./build
        run: ninja -j4 install
      - name: Run Talipot unit tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./build
          run: ninja tests
